-- EMPLOYEE TABLE
 CREATE TABLE `employee` (
  `EMP_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) DEFAULT NULL,
  `DOB` date DEFAULT NULL,
  `PHONE_NUMBER` bigint DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `MANAGER_ID` int DEFAULT NULL,
  `GENDER` enum('MALE','FEMALE','OTHER') DEFAULT 'OTHER',
  `ROLE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`EMP_ID`),
  KEY `MANAGER_ID` (`MANAGER_ID`),
  CONSTRAINT `employee_ibfk_1` FOREIGN KEY (`MANAGER_ID`) REFERENCES `employee` (`EMP_ID`)



-- LEAVE_TYPE TABLE
 CREATE TABLE `leave_type` (
  `LEAVE_TYPE_ID` int NOT NULL AUTO_INCREMENT,
  `LEAVE_TYPE` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(1000) DEFAULT NULL,
  `MAX_LEAVE_DAYS_ALLOWED` int DEFAULT NULL,
  `APPLICABLE_GENDER` enum('MALE','FEMALE','BOTH') DEFAULT 'BOTH',
  PRIMARY KEY (`LEAVE_TYPE_ID`)

-- LEAVE_REQUEST TABLE
 CREATE TABLE `leave_request` (
  `LEAVE_REQUEST_ID` int NOT NULL AUTO_INCREMENT,
  `EMP_ID` int DEFAULT NULL,
  `LEAVE_TYPE_ID` int DEFAULT NULL,
  `LEAVE_REASON` varchar(1000) DEFAULT NULL,
  `FROM_DATE` date DEFAULT NULL,
  `TO_DATE` date DEFAULT NULL,
  `DATE_OF_APPLICATION` date DEFAULT NULL,
  `LEAVE_STATUS` enum('APPROVED','REJECTED','PENDING','CANCELLED') DEFAULT NULL,
  `DATE_OF_ACTION` date DEFAULT NULL,
  `TOTAL_DAYS` int DEFAULT NULL,
  PRIMARY KEY (`LEAVE_REQUEST_ID`),
  KEY `EMP_ID` (`EMP_ID`),
  KEY `LEAVE_TYPE_ID` (`LEAVE_TYPE_ID`),
  CONSTRAINT `leave_request_ibfk_1` FOREIGN KEY (`EMP_ID`) REFERENCES `employee` (`EMP_ID`),
  CONSTRAINT `LEAVE_REQUEST_IBFK_2` FOREIGN KEY (`LEAVE_TYPE_ID`) REFERENCES `leave_type` (`LEAVE_TYPE_ID`)

-- EMPLOYEE_PASSWORD TABLE
CREATE TABLE IF NOT EXISTS EMPLOYEE_PASSWORD (
    EMPLOYEE_PASSWORD_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMP_ID INT,
    EMAIL_ID VARCHAR(255),
    PASSWORD VARCHAR(255),
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);

--EMPLOYEE LEAVE SUMMARY TABLE
 CREATE TABLE `employee_leave_summary` (
  `SUMMARY_ID` int NOT NULL AUTO_INCREMENT,
  `EMP_ID` int NOT NULL,
  `LEAVE_TYPE_ID` int NOT NULL,
  `LEAVE_TYPE` varchar(255) NOT NULL,
  `PENDING
  _LEAVES` int DEFAULT '0',
  `TOTAL_LEAVES_TAKEN` int DEFAULT '0',
  `LAST_UPDATED` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SUMMARY_ID`),
  KEY `EMP_ID` (`EMP_ID`),
  KEY `LEAVE_TYPE_ID` (`LEAVE_TYPE_ID`),
  CONSTRAINT `employee_leave_summary_ibfk_1` FOREIGN KEY (`EMP_ID`) REFERENCES `employee` (`EMP_ID`),
  CONSTRAINT `employee_leave_summary_ibfk_2` FOREIGN KEY (`LEAVE_TYPE_ID`) REFERENCES `leave_type` (`LEAVE_TYPE_ID`)

-- HOLIDAYS TABLE
 CREATE TABLE `holidays` (
  `HOLIDAY_ID` int NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `HOLIDAY_DATE` date NOT NULL,
  `DESCRIPTION` text,
  PRIMARY KEY (`HOLIDAY_ID`)


-- USER_COOKIES TABLE
CREATE TABLE IF NOT EXISTS EMPLOYEE_COOKIES (
    EMPLOYEE_COOKIES_ID INT AUTO_INCREMENT PRIMARY KEY,
    COOKIE_NAME VARCHAR(255) NOT NULL,
    COOKIE_VALUE VARCHAR(255) NOT NULL,
    EMP_ID INT NOT NULL,
    FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);
